### ISSUE TITLE
What is the font of the screenshot in the description?

### ISSUE THREAD

**Issue by schlace** [xenkuo/ccpp_theme#1]

**Comment by schlace** [comment]
@xenkuo Please

**Comment by schlace** [comment]
@xenkuo  🙏🙏🙏🙏🙏🙏

**Comment by xenkuo** [comment]
I'm using Cascadia Mono, but it's a font family, here's the repo: https://github.com/microsoft/cascadia-code

**Comment by xenkuo** [comment]
I love the font, MS makes it, also Windows Terminal use it as the default font type.
