### ISSUE TITLE
Is this underline correctly?

### ISSUE THREAD

**Issue by lixiyas** [xenkuo/ccpp_theme#2]
Thank you so much for designing this theme, and I just update from c enhanced theme to this new one.

But I find that pointer operators are sometimes misidentified, and ">" or "<" are easily confused with ">=“ and ”<=“ when underlined, as are use font wiht ligatures.But I didn't actually use a ligature font.

Can you give me some suggestions or is this need to be improved?

![企业微信截图_16837759233182](https://github.com/xenkuo/ccpp_theme/assets/37391438/1c2d4d3a-3871-4eec-9433-30aad1c418eb)

**Comment by xenkuo** [comment]
I noticed this issue as well. Adding underline style to logic operators is to distinguish && || with & |, but this does have side effect to symbols like > and <.

Maybe later we could change the style of logic operators, let's wait a little bit to see if there's more users have the same feedback. Imo, the user knows if they are using ligature or not or at least knows how >= and <= display, so may not so confused 😃 

To distinguish && || with & | is really a big feature as well, very how to make the balance...

By the way, which lsp your are using? Why -> be recognized as two tokens? Normally MS C/C++ lsp is slow and less token type recognized, but much accurate, the clangd is fast but seems can't handle complex code syntax properly.

**Comment by xenkuo** [comment]
I've updated some design of the theme, less underline style is used now, including the case you mentioned.
The logical and comparison operators still have a emphasized style: they are using red color. so we have a temporary balance now. :)

**Comment by lixiyas** [comment]
Thanks
