### ISSUE TITLE
函数参数和函数内部的临时变量，能不能加不同的颜色区分？

### ISSUE THREAD

**Issue by chenls** [xenkuo/ccpp_theme#3]
函数参数和函数内部的临时变量，能不能加不同的颜色区分？

**Comment by xenkuo** [comment]
技术上是可以区分内部临时变量和函数参数的，只是目前的设计只加了斜体表示是参数。原因是没有其他的颜色可以给参数用了，而且这两者也有相通性，所以只加斜体应该是合理的。

如果你有特定的需求，可以在vscode的setting里手动添加，可以参考：https://code.visualstudio.com/api/extension-guides/color-theme#syntax-colors

**Comment by chenls** [comment]
您好！您的来信已收悉，我将尽快处理！谢谢！

**Comment by whystopped** [comment]
@xenkuo 让函数内部的临时变量就用普通的白色可不可以（深色模式下），目前看来白色用得不多？

**Comment by chenls** [comment]
您好！您的来信已收悉，我将尽快处理！谢谢！

**Comment by xenkuo** [comment]
> @xenkuo 让函数内部的临时变量就用普通的白色可不可以（深色模式下），目前看来白色用得不多？

白色用的少的原因是深色背景下白色对比度太大了。
如果确实有这方面需求可以参考vscode的主题自定义配置，把相关的token改成自己喜欢的颜色就可以了。登录vscode后也可以同步，也挺方便的。

**Comment by chenls** [comment]
您好！您的来信已收悉，我将尽快处理！谢谢！
